repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        files: ^(games_library_api|tests)/.+\.py$

      - id: isort
        name: isort
        entry: isort
        language: system
        files: ^(games_library_api|tests)/.+\.py$

      - id: ruff
        name: ruff
        entry: ruff check --fix
        language: system
        files: ^(games_library_api|tests)/.+\.py$

      - id: mypy
        name: mypy
        entry: mypy
        language: system
        files: ^(games_library_api|tests)/.+\.py$

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.3.0'
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: detect-private-key
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: double-quote-string-fixer
      - id: end-of-file-fixer
      - id: name-tests-test
        files: ^(tests)/.+\.py$
        exclude: ^(tests).+(mock|util|constant|fixtur).*(\.py)$
        args:
          - '--pytest-test-first'
      - id: trailing-whitespace
        exclude: ^.+(\.md)$
