version: "3.9"
services:
  nginx:
    image: nginx:1.17
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/www:/var/www/certbot/:ro

    ports:
      - 80:90
      - 443:443
    restart: always
    depends_on:
      - backend
      - frontend

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
<<<<<<< HEAD


=======
      
>>>>>>> feed2061c8936855c44620dae0683715ebb070e3
  db:
    image: postgres:15.4
    container_name: database
    env_file:
      - .env
    ports:
      - "5433:5432"

  # backend:
  #   build:
  #     context: ./backend/
  #   env_file:
  #     - .env
  #   container_name: backend
  #   image: backend

  #   command: bash -c "gunicorn -w 4 -k uvicorn.workers.UvicornWorker games_library_api.main:make_app --bind 0.0.0.0:8888"
  #   depends_on:
  #     - db

  # frontend:
  #   build:
  #     context: ./gamification/
  #     dockerfile: ./Dockerfile
  #   restart: always
  #   env_file:
  #     - .env
  #   container_name: frontend

  #   depends_on:
  #     - backend
