version: "3.7"
services:
  db:
    image: postgres:15
    container_name: db
    ports:
      - "5433:5432"
    env_file:
      - .env-prod
  app:
    build:
      context: games_library_api/
    env_file:
      - .env-prod
    container_name: games_library_api
    ports:
      - "8000:8000"
    command: bash -c "alembic revision --autogenerate && alembic upgrade head && gunicorn -w 4 -k uvicorn.workers.UvicornWorker games_library_api.main:make_app --bind 0.0.0.0:8000"
    depends_on:
      - db
  frontend:
    build: frontend/
    container_name: frontend
    depends_on:
      - app
    network_mode: host