version: "3.9"
services:
  db:
    image: postgres:15.4
    container_name: database
    env_file:
      - .env
    ports:
      - "5433:5432"

  app:
    build:
      context: backend/
    env_file:
      - .env-prod
    container_name: backend
    image: backend
    ports:
      - "8000:8000"
    command: bash -c "gunicorn -w 4 -k uvicorn.workers.UvicornWorker backend.main:make_app --bind 0.0.0.0:8000"
    depends_on:
      - db

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=mokybrow@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend/
      dockerfile: ./Dockerfile
    restart: always
    env_file:
      - .env-prod
    container_name: frontend
    ports:
      - "127.0.0.1:3000:3000"
    expose:
      - 3000
    depends_on:
      - app