version: "3.9"
services:
  nginx:
    image: nginx:1.17
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:90
      - 443:443
    restart: always
    depends_on:
      - backend
      - frontend

  db:
    image: postgres:15.4
    container_name: database
    env_file:
      - .env-prod
    ports:
      - "5433:5432"

  backend:
    build:
      context: games_library_api/
    env_file:
      - .env-prod
    container_name: backend
    image: backend

    command: bash -c "gunicorn -w 4 -k uvicorn.workers.UvicornWorker backend.main:make_app --bind 0.0.0.0:8888"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend/
      dockerfile: ./Dockerfile
    restart: always
    env_file:
      - .env-prod
    container_name: frontend

    depends_on:
      - backend


