version: "3.9"
services:
  nginx:
    image: nginx:1.17
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - app
      - frontend

  db:
    image: postgres:15.4
    container_name: database
    env_file:
      - .env
    ports:
      - "5433:5432"

  app:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    env_file:
      - .env
    container_name: backend
    image: backend
    ports:
      - "8888:8888"
    command: bash -c "gunicorn -w 4 -k uvicorn.workers.UvicornWorker games_library_api.main:make_app --bind 0.0.0.0:8888"
    depends_on:
      - db

  frontend:
    build:
      context: ./gamification
      dockerfile: ./Dockerfile
    restart: always
    env_file:
      - .env
    container_name: frontend
    ports:
      - "127.0.0.1:3000:3000"
    expose:
      - 3000
    depends_on:
      - app

