"""empty message

Revision ID: 08c0e216329b
Revises: 05eb9f8153b6
Create Date: 2023-10-12 20:01:15.145207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08c0e216329b'
down_revision: Union[str, None] = '05eb9f8153b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_activity', sa.Column('username', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_activity', 'username')
    # ### end Alembic commands ###
