"""изменил уникальность колонки

Revision ID: 116d4ebc447b
Revises: 96347b80b89b
Create Date: 2023-08-29 22:07:50.615736

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '116d4ebc447b'
down_revision: Union[str, None] = '96347b80b89b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('list_slug_key', 'list', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('list_slug_key', 'list', ['slug'])
    # ### end Alembic commands ###
