"""new rules for field

Revision ID: 147f4e0f16be
Revises: d37a5a7af89f
Create Date: 2023-08-28 21:09:51.779922

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "147f4e0f16be"
down_revision: Union[str, None] = "d37a5a7af89f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "like", ["user_id"])
    op.create_unique_constraint(None, "passed", ["user_id"])
    op.create_unique_constraint(None, "wantplay", ["user_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "wantplay", type_="unique")
    op.drop_constraint(None, "passed", type_="unique")
    op.drop_constraint(None, "like", type_="unique")
    # ### end Alembic commands ###
