"""empty message

Revision ID: 21a418e19eb9
Revises: d616fc2a971a
Create Date: 2023-10-09 20:28:13.385860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21a418e19eb9'
down_revision: Union[str, None] = 'd616fc2a971a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('review_like', 'review_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('review_like', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('review_like', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('review_like', 'review_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
