"""new rules for field

Revision ID: 2f0849c9fd9a
Revises: b013fc8db908
Create Date: 2023-08-28 21:32:37.148868

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2f0849c9fd9a"
down_revision: Union[str, None] = "b013fc8db908"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("game", sa.Column("release", sa.DateTime(), nullable=False))
    op.add_column("game", sa.Column("platform", sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("game", "platform")
    op.drop_column("game", "release")
    # ### end Alembic commands ###
