"""empty message

Revision ID: 2fa779822155
Revises: f3f318031e43
Create Date: 2023-10-04 19:08:41.573725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fa779822155'
down_revision: Union[str, None] = 'f3f318031e43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('follower', sa.Column('id', sa.UUID(), nullable=False))
    op.add_column('review_like', sa.Column('id', sa.UUID(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review_like', 'id')
    op.drop_column('follower', 'id')
    # ### end Alembic commands ###
