"""empty message

Revision ID: 3fba65a44bf7
Revises: d0f4af31f56d
Create Date: 2023-10-04 23:06:10.282264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fba65a44bf7'
down_revision: Union[str, None] = 'd0f4af31f56d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('follower', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('follower', 'follower_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_foreign_key(None, 'follower', 'user', ['follower_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'follower', type_='foreignkey')
    op.alter_column('follower', 'follower_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('follower', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
