"""user_db

Revision ID: 40db087e7b31
Revises: 8e574c0473e4
Create Date: 2023-08-24 23:00:58.806887

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "40db087e7b31"
down_revision: Union[str, None] = "8e574c0473e4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("name", sa.String(), nullable=False))
    op.add_column("user", sa.Column("surname", sa.String(), nullable=True))
    op.add_column("user", sa.Column("birthdate", sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "birthdate")
    op.drop_column("user", "surname")
    op.drop_column("user", "name")
    # ### end Alembic commands ###
