"""empty message

Revision ID: 43e6e698bbae
Revises: 51dc23f39005
Create Date: 2023-10-03 20:01:39.492407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43e6e698bbae'
down_revision: Union[str, None] = '51dc23f39005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('playtime', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'playtime')
    # ### end Alembic commands ###
