"""empty message

Revision ID: 51dc23f39005
Revises: 4c62599a6554
Create Date: 2023-10-03 19:58:47.972051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51dc23f39005'
down_revision: Union[str, None] = '4c62599a6554'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('cover', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('release', sa.DateTime(), nullable=False),
    sa.Column('platform', sa.JSON(), nullable=False),
    sa.Column('parent_platform', sa.JSON(), nullable=False),
    sa.Column('genre', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('esrb_rating', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_foreign_key(None, 'like_game', 'game', ['game_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'list_game', 'game', ['game_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'passed_game', 'game', ['game_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'review', 'game', ['game_id'], ['id'], ondelete='CASCADE')
    op.add_column('user', sa.Column('subscriber', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'wantplay_game', 'game', ['game_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wantplay_game', type_='foreignkey')
    op.drop_column('user', 'subscriber')
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.drop_constraint(None, 'passed_game', type_='foreignkey')
    op.drop_constraint(None, 'list_game', type_='foreignkey')
    op.drop_constraint(None, 'like_game', type_='foreignkey')
    op.drop_table('game')
    # ### end Alembic commands ###
