"""a

Revision ID: 68bc65cbd9fa
Revises: 116d4ebc447b
Create Date: 2023-09-02 16:20:03.105575

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '68bc65cbd9fa'
down_revision: str | None = '116d4ebc447b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
