"""empty message

Revision ID: 6edc1607222d
Revises: 91a0f93b656d
Create Date: 2023-10-05 20:21:09.942880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6edc1607222d'
down_revision: Union[str, None] = '91a0f93b656d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('follower', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('follower', 'follower_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('follower', 'follower_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('follower', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
