"""empty message

Revision ID: 7d6689421396
Revises: 08c0e216329b
Create Date: 2023-10-12 20:10:17.321635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d6689421396'
down_revision: Union[str, None] = '08c0e216329b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_activity', sa.Column('slug', sa.String(), nullable=False))
    op.drop_column('user_activity', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_activity', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('user_activity', 'slug')
    # ### end Alembic commands ###
