"""empty message

Revision ID: 8f95b62a4bd9
Revises: 6edc1607222d
Create Date: 2023-10-05 21:01:47.854915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f95b62a4bd9'
down_revision: Union[str, None] = '6edc1607222d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('follower', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('follower', 'follower_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('follower', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('follower', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    op.alter_column('follower', 'follower_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('follower', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
