"""empty message

Revision ID: 91a0f93b656d
Revises: 3fba65a44bf7
Create Date: 2023-10-05 20:16:14.898070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91a0f93b656d'
down_revision: Union[str, None] = '3fba65a44bf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('follower', sa.Column('id', sa.UUID(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('follower', 'id')
    # ### end Alembic commands ###
