"""добавил каскадное удаление данных

Revision ID: 96347b80b89b
Revises: 1b92955a965a
Create Date: 2023-08-29 21:13:40.150381

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '96347b80b89b'
down_revision: str | None = '1b92955a965a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('list', sa.Column('slug', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'list', ['slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'list', type_='unique')
    op.drop_column('list', 'slug')
    # ### end Alembic commands ###
