"""user_db

Revision ID: 98170eff5578
Revises: 6bbcb73b3fa3
Create Date: 2023-08-24 23:06:03.437001

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "98170eff5578"
down_revision: Union[str, None] = "6bbcb73b3fa3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("user_hashed_password_key", "user", type_="unique")
    op.create_unique_constraint(None, "user", ["username"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="unique")
    op.create_unique_constraint("user_hashed_password_key", "user", ["hashed_password"])
    # ### end Alembic commands ###
