"""empty message

Revision ID: 9c2a860d269a
Revises: 
Create Date: 2023-10-09 08:06:20.507581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c2a860d269a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('like_game', 'list_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('like_game', 'game_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('passed_game', 'list_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('passed_game', 'game_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.add_column('user', sa.Column('registr_at', sa.DateTime(), nullable=True))
    op.alter_column('wantplay_game', 'list_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('wantplay_game', 'game_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wantplay_game', 'game_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('wantplay_game', 'list_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('user', 'registr_at')
    op.alter_column('passed_game', 'game_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('passed_game', 'list_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('like_game', 'game_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('like_game', 'list_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
