"""empty message

Revision ID: 9f44549136c2
Revises: 5c5d1c320199
Create Date: 2023-10-23 03:14:04.692111

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9f44549136c2'
down_revision: Union[str, None] = '5c5d1c320199'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'created_at')
    # ### end Alembic commands ###
