"""new rules for field

Revision ID: b013fc8db908
Revises: 147f4e0f16be
Create Date: 2023-08-28 21:18:19.303931

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b013fc8db908"
down_revision: Union[str, None] = "147f4e0f16be"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("game", sa.Column("slug", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("game", "slug")
    # ### end Alembic commands ###
