"""empty message

Revision ID: b4f75262b0df
Revises: 8f95b62a4bd9
Create Date: 2023-10-07 21:12:05.690585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4f75262b0df'
down_revision: Union[str, None] = '8f95b62a4bd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('like_game', 'list_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('like_game', 'game_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('passed_game', 'list_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('passed_game', 'game_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('wantplay_game', 'list_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('wantplay_game', 'game_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wantplay_game', 'game_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('wantplay_game', 'list_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('passed_game', 'game_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('passed_game', 'list_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('like_game', 'game_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('like_game', 'list_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
