"""new rules for field

Revision ID: bae60601a18d
Revises: 2f0849c9fd9a
Create Date: 2023-08-28 21:52:23.762857

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bae60601a18d"
down_revision: Union[str, None] = "2f0849c9fd9a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "game", ["slug"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "game", type_="unique")
    # ### end Alembic commands ###
