"""empty message

Revision ID: c028a268f880
Revises: cb0b7b7fe272
Create Date: 2023-09-03 19:29:00.965345

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c028a268f880'
down_revision: Union[str, None] = 'cb0b7b7fe272'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('genre', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'genre')
    # ### end Alembic commands ###
