"""a

Revision ID: c3ec056ebf4b
Revises: a9dc503f9d78
Create Date: 2023-08-27 14:39:12.067867

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c3ec056ebf4b"
down_revision: Union[str, None] = "a9dc503f9d78"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("list", "cover", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("list", "cover", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
