"""empty message

Revision ID: c83960a78115
Revises: 0c4dcb9d1e33
Create Date: 2023-10-22 11:19:19.495572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c83960a78115'
down_revision: Union[str, None] = '0c4dcb9d1e33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('cover', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'cover')
    # ### end Alembic commands ###
