"""empty message

Revision ID: d0f4af31f56d
Revises: 2fa779822155
Create Date: 2023-10-04 19:24:40.156609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0f4af31f56d'
down_revision: Union[str, None] = '2fa779822155'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('follower_follower_id_fkey', 'follower', type_='foreignkey')
    op.drop_column('follower', 'id')
    op.drop_column('review_like', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review_like', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('follower', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('follower_follower_id_fkey', 'follower', 'user', ['follower_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
