"""delete column

Revision ID: d37a5a7af89f
Revises: f997aefcd307
Create Date: 2023-08-27 20:15:02.715830

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d37a5a7af89f"
down_revision: Union[str, None] = "f997aefcd307"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("list_user_id_fkey", "list", type_="foreignkey")
    op.drop_column("list", "user_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "list", sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=True)
    )
    op.create_foreign_key("list_user_id_fkey", "list", "user", ["user_id"], ["id"])
    # ### end Alembic commands ###
