"""empty message

Revision ID: d616fc2a971a
Revises: 9c2a860d269a
Create Date: 2023-10-09 20:22:02.470920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd616fc2a971a'
down_revision: Union[str, None] = '9c2a860d269a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review_like', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review_like', 'created_at')
    # ### end Alembic commands ###
