"""новые таблицы

Revision ID: e23716e2d632
Revises: 3362da42650c
Create Date: 2023-08-29 18:55:16.003413

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e23716e2d632'
down_revision: Union[str, None] = '3362da42650c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'list_game',
        sa.Column('list_id', sa.UUID(), nullable=True),
        sa.Column('game_id', sa.UUID(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ['game_id'],
            ['game.id'],
        ),
        sa.ForeignKeyConstraint(
            ['list_id'],
            ['list.id'],
        ),
    )
    op.create_table(
        'list_user',
        sa.Column('list_id', sa.UUID(), nullable=True),
        sa.Column('user_id', sa.UUID(), nullable=True),
        sa.Column('added', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ['list_id'],
            ['list.id'],
        ),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['user.id'],
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('list_user')
    op.drop_table('list_game')
    # ### end Alembic commands ###
