"""empty message

Revision ID: e3c5778b29b9
Revises: 
Create Date: 2023-10-20 09:12:45.482004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3c5778b29b9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('list', sa.Column('title', sa.String(), nullable=False))
    op.drop_column('list', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('list', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('list', 'title')
    # ### end Alembic commands ###
