"""empty message

Revision ID: e96aadf798bc
Revises: aa3556b135e3
Create Date: 2023-10-14 18:36:20.612759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e96aadf798bc'
down_revision: Union[str, None] = 'aa3556b135e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('platform_name', sa.ARRAY(sa.String()), nullable=True))
    op.alter_column('game', 'release',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('game', 'playtime',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('game', 'platform',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)
    op.alter_column('game', 'parent_platform',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)
    op.alter_column('game', 'tags',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game', 'tags',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)
    op.alter_column('game', 'parent_platform',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)
    op.alter_column('game', 'platform',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)
    op.alter_column('game', 'playtime',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('game', 'release',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('game', 'platform_name')
    # ### end Alembic commands ###
