"""add tables

Revision ID: f2052e85f959
Revises: d12f63c73c25
Create Date: 2023-08-26 22:16:36.781957

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f2052e85f959"
down_revision: Union[str, None] = "d12f63c73c25"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("gender", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "gender")
    # ### end Alembic commands ###
