"""empty message

Revision ID: 4504ac1a4df3
Revises: 309336472c87
Create Date: 2023-11-16 11:05:38.571715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4504ac1a4df3'
down_revision: Union[str, None] = '309336472c87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('snippet', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'snippet')
    # ### end Alembic commands ###
