"""empty message

Revision ID: 772748fd9d93
Revises: 
Create Date: 2023-11-08 14:12:01.254326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '772748fd9d93'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_article_id'), 'article', ['id'], unique=False)
    op.drop_constraint('game_slug_key', 'game', type_='unique')
    op.create_index(op.f('ix_game_id'), 'game', ['id'], unique=False)
    op.create_index(op.f('ix_game_slug'), 'game', ['slug'], unique=True)
    op.drop_constraint('user_username_key', 'user', type_='unique')
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.create_unique_constraint('user_username_key', 'user', ['username'])
    op.drop_index(op.f('ix_game_slug'), table_name='game')
    op.drop_index(op.f('ix_game_id'), table_name='game')
    op.create_unique_constraint('game_slug_key', 'game', ['slug'])
    op.drop_index(op.f('ix_article_id'), table_name='article')
    # ### end Alembic commands ###
